### ISSUE TITLE
CCB-132 Fix mismatch between context object types and values of <type> in <Observing_System_Component> class

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS-Incubator/pds4-information-model#103]
https://pds-jira.jpl.nasa.gov/browse/CCB-138

The list of valid values for the <type> attribute in the <Observing_System_Component> class should be reduced to Instrument, Host, Literature Search and Telescope. All other existing values should be deprecated. 

The definition of Host shall read as follows: The observing system component is a host or a member in a chain of hosts that ultimately contains an instrument that collects data. 

[CCB-138.pdf](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/3929816/CCB-138.pdf)

**Comment by jordanpadams** [comment]
@jshughes one other note: could you add the `CCB-xxx` to the issue title? this will pop up nicely in the changelog that way.

**Comment by jordanpadams** [comment]
@jshughes looks good. looks like a quick typo on CCB-138, but I think the point was good and the PR looks good as well.
