### ISSUE TITLE
Clean up IMTool/LDDTool UML/XMI file writer for MagicDraw UML Class Diagrams

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS-Incubator/pds4-information-model#109]
Clean up IMTool/LDDTool UML/XMI file writer for MagicDraw UML Class Diagrams

Deprecate
	- XMI2LabelSchemaWNamesDOM
	- XMI2LabelSchemaDOM
  - XMI2LabelSchema2DOM
  
Add
  - WriteUML25XMIFile.java

**Comment by rchenatjpl** [comment]
Is this something to test? I guess no. If yes, please let me know and explain how I would see this difference. Thanks.

**Comment by jshughes** [comment]
There is no need to test this change. This was part of the LDDTool conversion. Also, the PDS hardly uses the UML diagrams. I only create them to include them in the IM Spec as diagrams for additional documentation. Most of the changes were for other projects that actually require the diagrams.
