### ISSUE TITLE
CCB-256: Need method for providing permissible value definitions for external namespaces in Ingest_LDD

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS-Incubator/pds4-information-model#130]
https://pds-jira.jpl.nasa.gov/browse/CCB-256
[CCB-256.pdf](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4106402/CCB-256.pdf)

**Comment by rchenatjpl** [comment]
I followed SPmockup.txt in pds-jira...CCB-256, which constrains the values of local_reference_type to spectral_characteristics_to_array_object and something else. However, when I run lddtool -plM on the attached input file, the resulting .sch has nothing about local_reference_type. It is easily possible that I've done something wrong, but i don't know what.

% lddtool -plM ccb256lddtoolinput.xml
>>info    - LDDTOOL Version: 11.0.0
>>info    - IM Version Id: 1.14.0.0
>>info    - IM Namespace Id: pds
>>info    - IM Label Version Id: 1.20
>>info    - Date: Sun Mar 08 11:25:25 PDT 2020
>>info    - JAVAHOME: /Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home
>>info    - PARENT_DIR: /PDS4tools/lddtool
>>info    - SCRIPT_DIR: /PDS4tools/lddtool/bin
>>info    - LIB_DIR: /PDS4tools/lddtool/lib

>>warning - Class omitted from build - Class Identifier:0001_NASA_PDS_1.pds.Schematron_Rule
>>warning - Class omitted from build - Class Identifier:0001_NASA_PDS_1.pds.Schematron_Assert
>>info    - getMasterObjectDict - Found LDDToolSingletonClass - DMDocument.LDDToolSingletonDOMClass.title:Mission_Area
   WARNING  Init:  - Config.Properties Namespace Id Not Found:insight
   INFO     Init:  - Config.Properties Namespace Id Using:pds
   WARNING  Header:  - New steward has been specified:geo
   WARNING  Header:  - New namespace id has been specified:insight
>>info    - LDDTOOL Exit
>>info    - Exit


[PDS4_INSIGHT_1E00_1E00.sch.zip](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4303927/PDS4_INSIGHT_1E00_1E00.sch.zip)


[ccb256lddtoolinput.xml.zip](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4303914/ccb256lddtoolinput.xml.zip)

**Comment by rchenatjpl** [comment]
The attached file doesn't validate. It's the same attachment at before with something else cleaned up. I guess the fix is to add DD_Associate_External_Class after DD_Association and DD_Association_External

Or maybe nobody validates such files, i.e. they  just run lddtool on them without first validating the lddtool input files 

[ccb256lddtoolinput.xml.zip](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4308521/ccb256lddtoolinput.xml.zip)

**Comment by rchenatjpl** [comment]
The attached file ccb256lddtoolinput.xml now validates, which is good. The .xsd that lddtool creates from it looks good. However, the .sch has no restrictions on the element with the external namespace. It is very possible that ccb256lddtoolinput.xml is incorrect. But what should it look like? 
[Archive.zip](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4353108/Archive.zip)

**Comment by rchenatjpl** [comment]
I still can't get this to work. The Archive.zip I attached earlier has a DD_Associate_External_Class that includes DD_Permissible_Values, but those values are not showing up in the .sch that lddtool outputs. Can you tell me what's wrong with the input file ccb256lddtoolinput.xml or give me an example that works? Thanks.

**Comment by rchenatjpl** [comment]
Thanks for the help, Steve. OK, so now lddtool outputs a .sch file that reflects the input file. However, the .sch is not quite right. The attached ccb256b.xml file validates when it shouldn't. But if I hand-modify the .sch, validate fails correctly.

% lddtool -pl ccb256lddtoolinput.xml
>>info    - LDDTOOL Version: 11.2.2
>>info    - IM Version Id: 1.14.0.0
>>info    - IM Namespace Id: pds
>>info    - IM Label Version Id: 1.20
>>info    - Date: Tue Apr 07 13:55:49 PDT 2020
>>info    - JAVAHOME: /Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home
>>info    - PARENT_DIR: /PDS4tools/lddtool
>>info    - SCRIPT_DIR: /PDS4tools/lddtool/bin
>>info    - LIB_DIR: /PDS4tools/lddtool/lib
>>warning - Class omitted from build - Class Identifier:0001_NASA_PDS_1.pds.Schematron_Rule
>>warning - Class omitted from build - Class Identifier:0001_NASA_PDS_1.pds.Schematron_Assert
>>info    - getMasterObjectDict - Set LDDToolSingletonClass - DMDocument.LDDToolSingletonDOMClass.title:USER
   WARNING  Init:  - Config.Properties Namespace Id Not Found:insight
   INFO     Init:  - Config.Properties Namespace Id Using:pds
   INFO     Init:  - LDD Dictionary_Type Found:Mission
   WARNING  Header:  - New steward has been specified:geo
   WARNING  Header:  - New namespace id has been specified:insight
>>info    - LDDTOOL Exit
>>info    - Exit
% 
% 
% validate -x PDS4_PDS_1E00.xsd PDS4_INSIGHT_1E00_1E00.xsd -S PDS4_PDS_1E00.sch PDS4_INSIGHT_1E00_1E00.sch -t ccb256b.xml
PDS Validate Tool Report
Configuration:
   Version                       1.22.1
   Date                          2020-04-07T20:56:01Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/schema/ccb256b.xml]
   User Specified Schemas        [file:/Users/rchen/Desktop/schema/PDS4_PDS_1E00.xsd, file:/Users/rchen/Desktop/schema/PDS4_INSIGHT_1E00_1E00.xsd]
   User Specified Schematrons    [file:/Users/rchen/Desktop/schema/PDS4_PDS_1E00.sch, file:/Users/rchen/Desktop/schema/PDS4_INSIGHT_1E00_1E00.sch]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/schema/ccb256b.xml
        1 product validation(s) completed
  [snip...]
% 
% 
% diff PDS4_INSIGHT_1E00_1E00.sch PDS4_INSIGHT_1E00_1E00.handmodified.sch
2c2
<   
---
>   
28,29c28,29
<     <sch:rule context="local_reference_type">
<       <sch:assert test="every $ref in (insight:local_reference_type) satisfies $ref = ('spectral_characteristics_to_array_object', 'spectral_characteristics_to_table_object')">
---
>     <sch:rule context="insight:Observation_Information/pds:Local_Internal_Reference/pds:local_reference_type">
>       <sch:assert test=". = ('spectral_characteristics_to_array_object', 'spectral_characteristics_to_table_object')">
% 
% 
% validate -x PDS4_PDS_1E00.xsd PDS4_INSIGHT_1E00_1E00.xsd -S PDS4_PDS_1E00.sch PDS4_INSIGHT_1E00_1E00.handmodified.sch -t ccb256b.xml
PDS Validate Tool Report
Configuration:
   Version                       1.22.1
   Date                          2020-04-07T20:56:39Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/schema/ccb256b.xml]
   User Specified Schemas        [file:/Users/rchen/Desktop/schema/PDS4_PDS_1E00.xsd, file:/Users/rchen/Desktop/schema/PDS4_INSIGHT_1E00_1E00.xsd]
   User Specified Schematrons    [file:/Users/rchen/Desktop/schema/PDS4_PDS_1E00.sch, file:/Users/rchen/Desktop/schema/PDS4_INSIGHT_1E00_1E00.handmodified.sch]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Users/rchen/Desktop/schema/ccb256b.xml
      ERROR  [error.label.schematron]   line 66, 43: The attribute local_reference_type must be equal to one of the following values 'spectral_characteristics_to_array_object', 'spectral_characteristics_to_table_object'.
        1 product validation(s) completed
  [snip...]
% 
% 
% 
[Archive.zip](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4446978/Archive.zip)

**Comment by rchenatjpl** [comment]
grr, the stuff that looks like code in the middle of the last comment is just straight text that github is formatting.
