### ISSUE TITLE
CCB-220: Add ability to specify many source products via table.

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS-Incubator/pds4-information-model#135]
https://pds-jira.jpl.nasa.gov/browse/CCB-220

[CCB-220.pdf](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4252734/CCB-220.pdf)

**Comment by jordanpadams** [comment]
@jshughes not a big deal, but as a reminder, search through the already existing tickets prior to creating a new one for CCBs. I already had one created for CCB-220 - https://github.com/NASA-PDS-Incubator/pds4-information-model/issues/116
