### ISSUE TITLE
LDDtool: unescaped & in output .xml

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS-Incubator/pds4-information-model#141]
% lddtool -plM ccb204lddtoolinputa.xml
produces the attached .xsd. Line 57 of that file:
  <xs:pattern value='[0-9]{4}[A-Za-z0-9&\.]{5}[A-Za-z0-9\.]{9}[A-Z\.]'/>
causes validate to choke. I think that line should be
  <xs:pattern value='[0-9]{4}[A-Za-z0-9&amp;\.]{5}[A-Za-z0-9\.]{9}[A-Z\.]'/>

[x.tar.gz](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4291307/x.tar.gz)

**Comment by jshughes** [comment]
Good catch, the code that escapes pattern values was added. However, I am surprised that this bug was not reported by users before now. It does not seem directly related to any approved CCB for this Build.
