### ISSUE TITLE
LDDtool: exposed class has a component class with a component exposed class

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS-Incubator/pds4-information-model#142]
If I read CCB-204 correctly, this is a bug, but it's highly possible I read it incorrectly.

I think lddtool should throw an error on the attached, but it doesn't. Super_All_Info has component All_Info which has component Observation_Information, and Super_All_Info and Observation_Information are "exposed" (a term I didn't know about until I saw the error message when I set All_Info's element_flag to true as well).
[ccb204lddtoolinputa.xml.gz](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4291314/ccb204lddtoolinputa.xml.gz)

**Comment by jshughes** [comment]
Nice catch and test case. The validate code falsely assumed subclasses had been identified. To fix the problem the algorithm was changed to following "component_of" chain.
