### ISSUE TITLE
LDDTool: Setup and configure CI/CD and Nightly Builds

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS-Incubator/pds4-information-model#158]
We need snapshot releases for testing purposes.

**Comment by jordanpadams** [comment]
Per the Github Action at https://github.com/NASA-PDS-Incubator/pds4-information-model/blob/master/.github/workflows/maven.yml we have started CI/CD. Eventually, it would be great to deploy the gh-pages, but this is sufficient for now.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl not sure if this feeds into the new repo for building or not, but refining our snapshot / release candidate / release automation would be great. both from the java and python realms. for java, let me know if you need some GPG things to post to sonatype and I can add them as secret keys to the applicable repos.

**Comment by tloubrieu-jpl** [comment]
I think we could have a dev/snapshot version of the PDS build and when we build a release we will check that every sub-project latest version are available in stable release.

The deployment of actual artifact would be done by the existing repository with maven action, either on push event (dev/snapshot) or on tag (stable version).

I will move this comment in the new repository.

**Comment by jordanpadams** [comment]
This has been completed. See for example SNAPSHOT builds.

https://github.com/NASA-PDS/pds4-information-model/releases
