### ISSUE TITLE
LDDTool: Fixed the calculation of class extensions and restrictions

### ISSUE THREAD

**Issue by jshughes416** [NASA-PDS-Incubator/pds4-information-model#77]
Per request from Cristina, fixed the calculation of class extensions and restrictions IMG LDD Brightness Correction

**Comment by rchenatjpl** [comment]
What does this issue mean? How about an example? Anything?

**Comment by jordanpadams** [comment]
@jshughes416 can you help out @rchenatjpl?

**Comment by rchenatjpl** [comment]
I still don't get this and will still assume it's fixed.
