### ISSUE TITLE
LDDTool_XMLSchema_Fix_Null_In_Import_File_Name

### ISSUE THREAD

**Issue by jshughes416** [NASA-PDS-Incubator/pds4-information-model#79]
LDDTool bugfix - Problem: The value for IM Version Id in the XML Schema "import" file name was being set to "null".

**Comment by rchenatjpl** [comment]
what to test?

**Comment by jordanpadams** [comment]
@jshughes416 please help out here?

**Comment by rchenatjpl** [comment]
Yeah, I thought I could figure out where to see the effects of this fix, but nope.

**Comment by rchenatjpl** [comment]
I still don't know how to test this, so I say it's fixed.

**Comment by jshughes** [comment]
This bugfix was in 1D00. The problem was that LDDTool inserted a "NULL" into the XML Schema file name even though the version id was specified in Ingest_LDD, for example, PDS4_GEOM_null_1700. I have not heard of a problem since October so the bug seems to be fixed.

**Comment by rchenatjpl** [comment]
Great, glad to hear it. Thanks
