### ISSUE TITLE
LDDTool: XMLSchema Fix Null In Import Cleanup

### ISSUE THREAD

**Issue by jshughes416** [NASA-PDS-Incubator/pds4-information-model#81]
LDDTool general cleanup
  MasterDOMInfoModel - move test on testTrue outside of loop
  DOMDataType - setting this.nsTitle is not needed since it is set by this.setIdentifier
  DMDocument - added "exit" message
  XML4LabelSchemaDOM - get info for XML schema namespace declaration - add pds (common) as default
  WriteDOMSchematron - get info for XML schema namespace declaration - add pds (common) as default
  LDDDOMParser - added helpful comments.

**Comment by rchenatjpl** [comment]
As with #77, it's hard to know what to test.

**Comment by jordanpadams** [comment]
@jshughes416 please help out here?

**Comment by rchenatjpl** [comment]
Yes, I'll say this one is fixed as well, though I don't understand the problem or the solution.

**Comment by jordanpadams** [comment]
@rchenatjpl I think this is under the hood leading to outputs

**Comment by jshughes** [comment]
This is the issue where null was in the output file name PDS4_GEOM_null_1700. Here is the test file.

[PDS4_IMG_IngestLDD_190928_changeExtensionToXML.txt](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4463962/PDS4_IMG_IngestLDD_190928_changeExtensionToXML.txt)
