### ISSUE TITLE
Improve error handling for LDDTool processing of CTLI IngestLDD file

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS-Incubator/pds4-information-model#91]
LDDTool aborts while processing CTLI IngestLDD file. The reported error is Exception in thread "main" java.lang.ClassCastException: DOMAttr cannot be cast to DOMClass. Changed test for class name from MOF "AttrDefn" to DOM "DOMAttr".

**Comment by rchenatjpl** [comment]
What is CTLI? Can you send me or attach such an Ingest_LDD file? Thanks

**Comment by jshughes** [comment]
CLTI - Context Type List - Instrument - see https://pds.jpl.nasa.gov/datastandards/dictionaries/#ctli
The term"clti" is the namespace of the LDD.

**Comment by rchenatjpl** [comment]
Thanks. Since 1) I don't have the CTLI Ingest_LDD, and 2) lddtool obviously was able to process it, I'll skip testing this as well.

**Comment by jordanpadams** [comment]
@rchenatjpl I think that is fine. we will eventually get our hands on the IngestLDD, but if Lyle and Co tested it, we can consider this good for now.

**Comment by jshughes** [comment]
I agree, at some time the Ingest_LDDs should under configuration management in GitHub.

**Comment by jordanpadams** [comment]
@rchenatjpl just as an FYI, the latest ZIP posted https://pds.nasa.gov/datastandards/dictionaries/ctli/v1/PDS4_CTLI_1D00_1101.zip. not sure you really need to test this, but just a heads up
