### ISSUE TITLE
Update LDDTool to write the PDS4 Data Dictionary (DocBook) for multiple LDDs

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS-Incubator/pds4-information-model#93]
Update LDDTool to write the PDS4 Data Dictionary (DocBook) for multiple LDDS. Multiple LDDs can now be stacked to produce a combined PDS4 Data Dictionary.

**Comment by rchenatjpl** [comment]
1) Is the output docbook the xml version of the Information Model Specification, https://pds.jpl.nasa.gov/datastandards/documents/im/current/index_1D00.html?
2) Should the output docbook include anything from the input Ingest_LDD for lddtool? I didn't see any.
3) Do you know an easy way to view or convert the docbook file?
Thanks

**Comment by rchenatjpl** [comment]
Regarding the previous comment's #2, I meant, does the docbook have anything from the LDD that's getting created? I didn't see any, but then I changed Ingest_LDD/namespace_id from "insight" to "geo", and that worked. Is this intentional? That would be fine. Is it documented somewhere? Eh, this stuff doesn't matter much except that I must test it. I won't chase this down any further.

**Comment by jordanpadams** [comment]
@jshughes can you comment? I thought this should work for both mission and discipline dictionaries but maybe not?

**Comment by rchenatjpl** [comment]
ah, an older version of lddtool showed what namespaces were available, and "insight" wasn't one of them. I guess it'd be nice to see what that list is, though since presumably Steve's the only one generating the DocBook, not having that info is a pain only for the tester.

**Comment by jshughes** [comment]
Yes, there is an issue assigned to me to reduce the number of messages written by LDDTool to the log. The list of namespaces was considered debugging information and is now only written when the debug flag is set to true. Unfortunately, the debug flag is set in the code.

However, the namespace registry can be found here: https://pds.jpl.nasa.gov/datastandards/schema/pds-namespace-registry.pdf

**Comment by jordanpadams** [comment]
@jshughes can we maybe output this in the Help (-h) info?

**Comment by jshughes** [comment]
Good idea, will add add this suggestion to the queue.
