### ISSUE TITLE
CCB-268 Add optional attribute to class Terminological_Entry

### ISSUE THREAD

**Issue by jshughes** [NASA-PDS-Incubator/pds4-information-model#99]
https://pds-jira.jpl.nasa.gov/browse/CCB-268

Add the optional attribute <skos_relation_name> to the class <Terminological_Entry> with cardinality [0..*]

[CCB-268.pdf](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/3923707/CCB-268.pdf)

**Comment by rchenatjpl** [comment]
OK, my test case says this issue passes because validate accepts my Ingest_LDD that has a skos_relation_name, but lddtool seems to ignore element Terminological_Entry altogether, including skos_relation_name. That might be as much as we can do now until we understand better what's desired.

**Comment by jordanpadams** [comment]
@rchenatjpl nothing came out in the JSON file?

**Comment by rchenatjpl** [comment]
Perhaps my input files are invalid? lddtool -plJ on each of the two attachments produces the same results except for the header comments.
[Archive.zip](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4441334/Archive.zip)

**Comment by rchenatjpl** [comment]
Perhaps my input files are invalid? lddtool -plJ on each of the two attachments produces the same results except for the header comments.
[Archive.zip](https://github.com/NASA-PDS-Incubator/pds4-information-model/files/4441336/Archive.zip)
